services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespw

    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ["/wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: